"""criar tabela de funcionarios

Revision ID: 11a766eba9e0
Revises: 5bccdb86a511
Create Date: 2021-11-10 17:14:08.226197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a766eba9e0'
down_revision = '5bccdb86a511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha_hash', sa.String(length=256), nullable=True),
    sa.Column('codigo', sa.Integer(), nullable=True),
    sa.Column('cargo', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('funcionario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funcionario_cargo'), ['cargo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funcionario_cargo'))

    op.drop_table('funcionario')
    # ### end Alembic commands ###
