"""criar campo de codigo do funcionario em atendimento

Revision ID: 6ac93cb9ebd1
Revises: 11a766eba9e0
Create Date: 2021-11-10 17:24:32.475299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac93cb9ebd1'
down_revision = '11a766eba9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_func', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_atendimento_codigo_func'), ['codigo_func'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atendimento_codigo_func'))
        batch_op.drop_column('codigo_func')

    # ### end Alembic commands ###
