"""criar tabela de clientes inicial

Revision ID: 879bb8d5d260
Revises: 
Create Date: 2021-11-01 11:25:02.245012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879bb8d5d260'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_cep'), 'cliente', ['cep'], unique=False)
    op.create_index(op.f('ix_cliente_cpf'), 'cliente', ['cpf'], unique=False)
    op.create_index(op.f('ix_cliente_email'), 'cliente', ['email'], unique=False)
    op.create_index(op.f('ix_cliente_endereco'), 'cliente', ['endereco'], unique=False)
    op.create_index(op.f('ix_cliente_nome'), 'cliente', ['nome'], unique=False)
    op.create_index(op.f('ix_cliente_telefone'), 'cliente', ['telefone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cliente_telefone'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_nome'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_endereco'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_email'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_cpf'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_cep'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
