"""adicionar campo de idade para pet e obs para atendimento

Revision ID: b56443185255
Revises: 9485e5bd8c8f
Create Date: 2021-11-07 13:23:05.958011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56443185255'
down_revision = '9485e5bd8c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atendimento', sa.Column('obs', sa.String(length=200), nullable=True))
    op.add_column('pet', sa.Column('idade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'idade')
    op.drop_column('atendimento', 'obs')
    # ### end Alembic commands ###
