"""criar tabela para gaiola

Revision ID: cf08715834ec
Revises: 6ac93cb9ebd1
Create Date: 2021-11-17 15:21:24.184963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf08715834ec'
down_revision = '6ac93cb9ebd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gaiola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gaiola', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gaiola_numero'), ['numero'], unique=False)

    with op.batch_alter_table('atendimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gaiola', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimento', schema=None) as batch_op:
        batch_op.drop_column('gaiola')

    with op.batch_alter_table('gaiola', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gaiola_numero'))

    op.drop_table('gaiola')
    # ### end Alembic commands ###
